# -*- coding: utf-8 -*-
"""teste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBUFt_zaHsbbBmOe49I2TT-ZIU2S6yOw
"""

numeros = [10, 23, 5, 8, 12, 33, 42, 7, 19, 28, 3, 16, 9, 50, 21]
media(numeros)
x = media(numeros)
print("A média dos números da lista é igual a: ", x)
NumeroMaior = max(numeros)
NumeroMenor = min(numeros)
print("O maior número da lista é ", NumeroMaior)
print("O menor número da lista é ", NumeroMenor)
cpar = 0
cimpar = 0
for n in numeros:
  if n % 2 == 0:
    cpar += 1
  else:
    cimpar += 1

print("Quantidade de números pares: ", cpar)